---
title: "Schedule"
output: html_document
---

### Agenda:

| Week              | Day 1                         | Day 2                      |
| :---------------- | :---------------------------- | :------------------------- |
|  Week 1           | Welcome, Intros, Objectives   | Day 1 recap                |
|                   | Projects and RStudio          | 02 - Wrangling Data        |
|                   | 01 - Visualize Data           |                            |
|                   |                               |                            |       
|  Week 2           | Welcome, Intros, Objectives   | Day 1 recap                |
|                   | 03 - More Wrangling           | 05 - Functions             | 
|                   | 04 - Statistical Outputs      | 06 - Loops                 | 
|                   |                               |                            |


# Week 1

***

### Day 1: Thursday, June 18, 2020

*  Session 00: Introduction 
    *   Zoom
    *   [RStudio Cloud](rstudio.cloud)
    *   Workflow tips and tricks
*  Session 01: Visualize
    *   Introduction and basics
    *   Mappings and aesthetics
    *   Facets
    *   Geoms, stat and position arguments
    *   What else can I do? (scales, `scale_color_brewer()`, titles and captions, themes, `ggThemeAssist`)
    *   Saving your plot

### Day 2: Friday, June 19, 2020

*  Day 1 Recap

*  Session 02: Wrangle

*  *Week 1 Homework*

***

# Week 2

### Day 1: Thursday, June 25, 2020

*  Welcome back and review of Week 1 Homework

*  Session 03: More Wrangling 

*  Session 04: Statistical Outputs


### Day 2: Friday, June 26, 2020

*  Day 1 Recap

*  Session 05: Functions

*  Session 06: Loops
